<a href="https://colab.research.google.com/github/rawanaldaneen/pytorch_row/blob/main/00_Pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
print(torch.__version__)


2.5.0+cu121


In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# Check the number of dimensions of vector
vector.ndim

1

In [ ]:
# Check shape of vector
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# Check number of dimensions
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#tensor
TENSOR=torch.tensor([[[1,2,3,],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim



3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR1=torch.tensor([[[1,1,1,2,3,4],[5,1,1,6,7,8],[9,1,1,10,11,12],[13,1,1,14,15,16],[17,1,1,18,19,20],[2,1,1,22,11,44]]])
TENSOR1

tensor([[[ 1,  1,  1,  2,  3,  4],
         [ 5,  1,  1,  6,  7,  8],
         [ 9,  1,  1, 10, 11, 12],
         [13,  1,  1, 14, 15, 16],
         [17,  1,  1, 18, 19, 20],
         [ 2,  1,  1, 22, 11, 44]]])

In [ ]:
TENSOR1.ndim

3

In [ ]:
TENSOR1.shape

torch.Size([1, 6, 6])

In [ ]:
M=torch.tensor([[[11,22,33],[1,2,3],[44,55,66]],[[17,2,3],[3,2,1],[2,2,1]]])
M


tensor([[[11, 22, 33],
         [ 1,  2,  3],
         [44, 55, 66]],

        [[17,  2,  3],
         [ 3,  2,  1],
         [ 2,  2,  1]]])

In [ ]:
M.ndim

3

In [ ]:
M.shape

torch.Size([2, 3, 3])

In [4]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.2763, 0.9379, 0.9452, 0.6316],
         [0.3237, 0.3347, 0.2818, 0.8446],
         [0.2755, 0.2364, 0.2667, 0.1930]]),
 torch.float32)

In [8]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,3,4)
random_tensor, random_tensor.dtype


(tensor([[[0.5304, 0.3133, 0.0090, 0.4653],
          [0.5346, 0.9440, 0.9417, 0.3211],
          [0.9195, 0.2567, 0.4422, 0.3566]],
 
         [[0.9654, 0.2115, 0.9290, 0.3053],
          [0.5527, 0.8239, 0.6007, 0.8920],
          [0.1910, 0.8158, 0.0399, 0.0583]],
 
         [[0.0551, 0.3083, 0.3682, 0.5037],
          [0.9163, 0.9697, 0.1785, 0.0755],
          [0.0013, 0.7956, 0.6148, 0.2972]]]),
 torch.float32)

In [12]:
# create random tensor of size (3,224,224)
random_image_size_tensor=torch.rand(size=(3,224,224))
random_image_size_tensor, random_image_size_tensor.dtype
random_image_size_tensor.ndim

3

In [13]:
# create zeros tensors and ones tensores
zeros=torch.zeros(5,6)
ones=torch.ones(7,7)
zeros,ones

(tensor([[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]))