<a href="https://colab.research.google.com/github/rawanaldaneen/pytorch_row/blob/main/00_Pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
print(torch.__version__)


2.5.0+cu121


In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# Check the number of dimensions of vector
vector.ndim

1

In [ ]:
# Check shape of vector
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# Check number of dimensions
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#tensor
TENSOR=torch.tensor([[[1,2,3,],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim



3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR1=torch.tensor([[[1,1,1,2,3,4],[5,1,1,6,7,8],[9,1,1,10,11,12],[13,1,1,14,15,16],[17,1,1,18,19,20],[2,1,1,22,11,44]]])
TENSOR1

tensor([[[ 1,  1,  1,  2,  3,  4],
         [ 5,  1,  1,  6,  7,  8],
         [ 9,  1,  1, 10, 11, 12],
         [13,  1,  1, 14, 15, 16],
         [17,  1,  1, 18, 19, 20],
         [ 2,  1,  1, 22, 11, 44]]])

In [ ]:
TENSOR1.ndim

3

In [ ]:
TENSOR1.shape

torch.Size([1, 6, 6])

In [ ]:
M=torch.tensor([[[11,22,33],[1,2,3],[44,55,66]],[[17,2,3],[3,2,1],[2,2,1]]])
M


tensor([[[11, 22, 33],
         [ 1,  2,  3],
         [44, 55, 66]],

        [[17,  2,  3],
         [ 3,  2,  1],
         [ 2,  2,  1]]])

In [ ]:
M.ndim

3

In [ ]:
M.shape

torch.Size([2, 3, 3])

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.2763, 0.9379, 0.9452, 0.6316],
         [0.3237, 0.3347, 0.2818, 0.8446],
         [0.2755, 0.2364, 0.2667, 0.1930]]),
 torch.float32)

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3,3,4)
random_tensor, random_tensor.dtype


(tensor([[[0.5304, 0.3133, 0.0090, 0.4653],
          [0.5346, 0.9440, 0.9417, 0.3211],
          [0.9195, 0.2567, 0.4422, 0.3566]],
 
         [[0.9654, 0.2115, 0.9290, 0.3053],
          [0.5527, 0.8239, 0.6007, 0.8920],
          [0.1910, 0.8158, 0.0399, 0.0583]],
 
         [[0.0551, 0.3083, 0.3682, 0.5037],
          [0.9163, 0.9697, 0.1785, 0.0755],
          [0.0013, 0.7956, 0.6148, 0.2972]]]),
 torch.float32)

In [ ]:
# create random tensor of size (3,224,224)
random_image_size_tensor=torch.rand(size=(3,224,224))
random_image_size_tensor, random_image_size_tensor.dtype
random_image_size_tensor.ndim

3

In [ ]:
# create zeros tensors and ones tensores
zeros=torch.zeros(5,6)
ones=torch.ones(7,7)
zeros,ones

(tensor([[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]]))

# Creating tensor of using arange and alike function


In [ ]:
one_to_fifty=torch.arange(start=1,end=51,step=3)
one_to_fifty

tensor([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [ ]:
ten_zeros=torch.zeros_like(input=one_to_fifty)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones=torch.ones_like(input=one_to_fifty)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
rand_tensor_number=torch.rand(2,4)
rand_tensor_number


tensor([[0.1956, 0.3152, 0.9564, 0.1532],
        [0.4274, 0.7423, 0.6768, 0.4508]])

In [ ]:
rand_tensor=torch.rand_like(input=rand_tensor_number)
rand_tensor

tensor([[0.8445, 0.2755, 0.4805, 0.0900],
        [0.4361, 0.3669, 0.7598, 0.9279]])

In [ ]:
# data type for tensor
float_32_tensor=torch.tensor([3.8,4.3,3.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor.dtype, float_32_tensor.device

(torch.float32, device(type='cpu'))

In [ ]:
# float 16
float_16_tensor=torch.tensor([3.0,6.0,2.2],
                             dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
#covert float 32 to 16
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.8008, 4.3008, 3.0000], dtype=torch.float16)

In [ ]:
#find out details about some tensor
some_tensor=torch.rand(3,4)
some_tensor
print(some_tensor)
print(f'DataType of Tensor: {some_tensor.dtype}')
print(f'Shape of Tensor:    {some_tensor.shape}')
print(f'Device of Tensor:   {some_tensor.device}')
print(f'Size of Tensor:     {some_tensor.size()}')

tensor([[0.6044, 0.6378, 0.2975, 0.7116],
        [0.4190, 0.2404, 0.9824, 0.1551],
        [0.9518, 0.1838, 0.9175, 0.1470]])
DataType of Tensor: torch.float32
Shape of Tensor:    torch.Size([3, 4])
Device of Tensor:   cpu
Size of Tensor:     torch.Size([3, 4])


Manipulating tensors (tensor operations)¶

These operations are often a wonderful dance between:

Addition
Substraction
Multiplication (element-wise)
Division
Matrix multiplication




In [ ]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply it by 10
tensor * 1000

tensor([1000, 2000, 3000])

In [ ]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

Matrix multiplication (is all you need)

In [4]:

tensor=torch.tensor([1,2,3])
print(tensor,'*',tensor)
print(f"equals: {tensor *tensor }")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals: tensor([1, 4, 9])


In [5]:
torch.matmul(tensor,tensor)

tensor(14)

In [7]:
%%time
value=0
for i in range(len(tensor)):
  value +=tensor[i]*tensor[i]
print(value)


tensor(14)
CPU times: user 3.22 ms, sys: 0 ns, total: 3.22 ms
Wall time: 3.07 ms


In [9]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.16 ms, sys: 10 µs, total: 1.17 ms
Wall time: 1.19 ms


tensor(14)

In [13]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))
torch.matmul(torch.rand(4,2), torch.rand(2,4))

tensor([[0.1686, 0.2539, 0.4198, 0.3245],
        [0.1594, 0.5611, 0.1241, 0.5626],
        [0.2308, 0.5717, 0.3841, 0.6228],
        [0.0502, 0.0474, 0.1489, 0.0742]])

In [16]:
tensor_A=torch.tensor(([1,2],
                      [3,4],
                      [5,6]))
tensor_B=torch.tensor(([1,2],
                      [3,4],
                      [5,6]))

In [19]:
print(f'Orginal Shape : Tensor_A {tensor_A.shape} , Tensor_B{tensor_B.shape}\n')
print(f'new Shape: Tensor_A {tensor_A.T.shape}, Tensor_B{tensor_B.shape}\n')
print(f' multipication : {tensor_A.T} *{tensor_B} <- inner dimention match \n')
print(f'output: \n')
output=torch.matmul(tensor_A.T,tensor_B)
print(output)
print(f'output: {output.shape}')

Orginal Shape : Tensor_A torch.Size([3, 2]) , Tensor_Btorch.Size([3, 2])

new Shape: Tensor_A torch.Size([2, 3]), Tensor_Btorch.Size([3, 2])

 multipication : tensor([[1, 3, 5],
        [2, 4, 6]]) *tensor([[1, 2],
        [3, 4],
        [5, 6]]) <- inner dimention match 

output: 

tensor([[35, 44],
        [44, 56]])
output: torch.Size([2, 2])
